export const galleryData = [
  { id: 1, type: "image", src: "/galleryImages/banner.jpeg" },
  { id: 2, type: "image", src: "/galleryImages/businesCard1.jpeg" },
  { id: 3, type: "image", src: "/galleryImages/businessCard2.jpeg" },
  { id: 4, type: "image", src: "/galleryImages/centerImage1.jpeg" },
  { id: 5, type: "image", src: "/galleryImages/centerImage2.jpeg" },
  { id: 6, type: "image", src: "/galleryImages/centerImage3.jpeg" },
  { id: 7, type: "image", src: "/galleryImages/couplingCare.jpeg" },
  { id: 8, type: "image", src: "/galleryImages/doc1.jpeg" },
  { id: 9, type: "image", src: "/galleryImages/doc2.jpeg" },
  { id: 10, type: "image", src: "/galleryImages/doc3.jpeg" },
  { id: 11, type: "image", src: "/galleryImages/doc4.jpeg" },
  { id: 12, type: "image", src: "/galleryImages/doctors2.jpeg" },
  { id: 13, type: "video", src: "/galleryImages/excersice.mp4" },
  { id: 14, type: "image", src: "/galleryImages/girl.jpeg" },
  { id: 15, type: "image", src: "/galleryImages/knee.jpeg" },
  { id: 16, type: "image", src: "/galleryImages/machine.jpeg" },
  { id: 17, type: "image", src: "/galleryImages/nihal_desk.jpeg" },
  { id: 18, type: "image", src: "/galleryImages/old_woemnExcercise.jpeg" },
  { id: 19, type: "image", src: "/galleryImages/old_wormenCare.jpeg" },
  { id: 20, type: "image", src: "/galleryImages/old_wormenKnee.jpeg" },
  { id: 21, type: "image", src: "/galleryImages/pressure_doc.jpeg" },
  { id: 22, type: "image", src: "/galleryImages/pressure_doc2.jpeg" },
  { id: 23, type: "image", src: "/galleryImages/taping.jpeg" },
  { id: 24, type: "image", src: "/galleryImages/tool.jpeg" },
];
